import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { useTheme } from 'react-native-paper';
import { Typography, Spacing, Radii, Shadows } from '../theme/colors';
import GlassCard from '../components/GlassCard';

interface Debt {
  fromName: string;
  toName: string;
  amount: number;
  groupName: string;
  currency: string;
  expenses: string[];
}

interface SettlementReminderScreenProps {
  navigation: any;
  route: {
    params: {
      debts?: Debt[];
    };
  };
}

const MOCK_DEBTS: Debt[] = [
  {
    fromName: 'Rahul',
    toName: 'You',
    amount: 850,
    groupName: 'Goa Trip 🏖️',
    currency: '₹',
    expenses: ['Hotel booking', 'Dinner at Beach Shack', 'Taxi'],
  },
  {
    fromName: 'Priya',
    toName: 'You',
    amount: 420,
    groupName: 'Office Lunch 🍱',
    currency: '₹',
    expenses: ['Lunch delivery', 'Chai'],
  },
];

const SettlementReminderScreen: React.FC<SettlementReminderScreenProps> = ({
  navigation,
  route,
}) => {
  const theme = useTheme();
  const customColors = (theme.colors as any).custom;

  const debts = route?.params?.debts || MOCK_DEBTS;
  const totalOwed = debts.reduce((sum, d) => sum + d.amount, 0);

  const generateWhatsAppMessage = (debt: Debt): string => {
    const expenseList = debt.expenses.map(e => `  • ${e}`).join('\n');
    return `Hi ${debt.fromName}! 👋\n\nJust a friendly reminder about our shared expenses from *${debt.groupName}*:\n\n${expenseList}\n\n💰 *Total you owe: ${debt.currency}${debt.amount.toFixed(2)}*\n\nYou can pay me via:\n📱 UPI: mohit@paytm\n\nPlease settle when you get a chance! Thanks 🙏\n\n_Sent via SplitSmart_`;
  };

  const generateBulkMessage = (): string => {
    const lines = debts.map(
      d => `• ${d.fromName}: ${d.currency}${d.amount.toFixed(2)} (${d.groupName})`
    );
    return `💸 *Settlement Summary*\n\nThe following people owe me money:\n\n${lines.join('\n')}\n\n📊 *Total: ${debts[0]?.currency || '₹'}${totalOwed.toFixed(2)}*\n\nPlease pay via UPI: mohit@paytm\n\n_Generated by SplitSmart_`;
  };

  const shareReminder = async (debt: Debt) => {
    const message = generateWhatsAppMessage(debt);
    try {
      await Share.share({
        message,
        title: `Payment Reminder — ${debt.fromName}`,
      });
    } catch {
      Alert.alert('Error', 'Could not open share sheet');
    }
  };

  const shareBulkReminder = async () => {
    const message = generateBulkMessage();
    try {
      await Share.share({
        message,
        title: 'SplitSmart — Settlement Summary',
      });
    } catch {
      Alert.alert('Error', 'Could not open share sheet');
    }
  };

  const copyToClipboard = (debt: Debt) => {
    Alert.alert('Copied!', 'Message copied to clipboard');
  };

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
      paddingHorizontal: Spacing.md,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 60,
      paddingBottom: Spacing.md,
    },
    backBtn: {
      width: 44,
      height: 44,
      borderRadius: Radii.full,
      backgroundColor: customColors.glass,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: customColors.glassBorder,
    },
    backIcon: { fontSize: 20, color: theme.colors.onBackground },
    title: {
      fontSize: Typography.sizes.xl,
      fontFamily: Typography.fontFamily.bold,
      color: theme.colors.onBackground,
      fontWeight: '700',
    },
    summaryCard: {
      marginBottom: Spacing.lg,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 8,
    },
    summaryLabel: {
      fontSize: Typography.sizes.xs,
      color: customColors.textMuted,
      fontFamily: Typography.fontFamily.medium,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    summaryAmount: {
      fontSize: Typography.sizes.xxl,
      fontFamily: Typography.fontFamily.bold,
      color: theme.colors.onSurface,
      marginTop: 2,
    },
    summaryEmoji: { fontSize: 36 },
    summarySubtitle: {
      fontSize: Typography.sizes.sm,
      color: customColors.textSecondary,
      fontFamily: Typography.fontFamily.regular,
      marginBottom: Spacing.md,
    },
    bulkShareBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: Radii.md,
      paddingVertical: 12,
      gap: 8,
      ...Shadows.fab,
      shadowColor: theme.colors.primary,
    },
    bulkShareIcon: { fontSize: 18 },
    bulkShareText: {
      fontSize: Typography.sizes.md,
      color: '#FFFFFF',
      fontFamily: Typography.fontFamily.semiBold,
      fontWeight: '700',
    },
    sectionTitle: {
      fontSize: Typography.sizes.md,
      fontFamily: Typography.fontFamily.semiBold,
      color: theme.colors.onBackground,
      marginBottom: Spacing.sm,
      fontWeight: '700',
    },
    debtCard: {
      marginBottom: Spacing.md,
      gap: Spacing.sm,
    },
    debtHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    avatarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: customColors.glassStrong,
      borderWidth: 2,
      borderColor: customColors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontSize: Typography.sizes.md,
      color: theme.colors.primary,
      fontFamily: Typography.fontFamily.bold,
      fontWeight: '700',
    },
    debtPersonName: {
      fontSize: Typography.sizes.md,
      color: theme.colors.onSurface,
      fontFamily: Typography.fontFamily.semiBold,
      fontWeight: '600',
    },
    debtGroup: {
      fontSize: Typography.sizes.xs,
      color: customColors.textMuted,
      fontFamily: Typography.fontFamily.regular,
    },
    debtAmountBadge: {
      backgroundColor: 'rgba(239,63,94,0.12)',
      borderRadius: Radii.md,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: customColors.negative,
    },
    debtAmountText: {
      fontSize: Typography.sizes.md,
      color: customColors.negative,
      fontFamily: Typography.fontFamily.bold,
      fontWeight: '700',
    },
    expenseList: {
      gap: 4,
      paddingLeft: 4,
      borderLeftWidth: 2,
      borderLeftColor: theme.colors.outline,
      paddingVertical: 4,
      marginLeft: 4,
    },
    expenseRow: {
      flexDirection: 'row',
      gap: 6,
      alignItems: 'center',
    },
    expenseDot: {
      color: theme.colors.primary,
      fontSize: 10,
    },
    expenseName: {
      fontSize: Typography.sizes.sm,
      color: customColors.textSecondary,
      fontFamily: Typography.fontFamily.regular,
    },
    messagePreview: {
      backgroundColor: theme.colors.surfaceVariant,
      borderRadius: Radii.md,
      padding: Spacing.sm,
      borderWidth: 1,
      borderColor: theme.colors.outline,
    },
    previewLabel: {
      fontSize: Typography.sizes.xs,
      color: customColors.textMuted,
      fontFamily: Typography.fontFamily.medium,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    previewText: {
      fontSize: Typography.sizes.xs,
      color: customColors.textSecondary,
      fontFamily: Typography.fontFamily.regular,
      lineHeight: 16,
    },
    actionRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    copyBtn: {
      paddingHorizontal: Spacing.md,
      paddingVertical: 10,
      backgroundColor: customColors.glass,
      borderRadius: Radii.md,
      borderWidth: 1,
      borderColor: theme.colors.outline,
    },
    copyBtnText: {
      fontSize: Typography.sizes.sm,
      color: customColors.textSecondary,
      fontFamily: Typography.fontFamily.medium,
    },
    shareBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: customColors.accentLight,
      borderRadius: Radii.md,
      paddingVertical: 10,
      gap: 6,
      ...Shadows.glow,
      shadowColor: customColors.accentLight,
    },
    shareBtnIcon: { fontSize: 16 },
    shareBtnText: {
      fontSize: Typography.sizes.sm,
      color: '#FFFFFF',
      fontFamily: Typography.fontFamily.semiBold,
      fontWeight: '600',
    },
    tipCard: {
      marginTop: Spacing.sm,
      gap: 6,
    },
    tipTitle: {
      fontSize: Typography.sizes.sm,
      color: theme.colors.onSurface,
      fontFamily: Typography.fontFamily.semiBold,
      marginBottom: 4,
      fontWeight: '600',
    },
    tipText: {
      fontSize: Typography.sizes.xs,
      color: customColors.textMuted,
      fontFamily: Typography.fontFamily.regular,
      lineHeight: 18,
    },
  });

  return (
    <View style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
            <Text style={styles.backIcon}>←</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Send Reminders</Text>
          <View style={{ width: 44 }} />
        </View>

        <GlassCard style={styles.summaryCard} variant="accent">
          <View style={styles.summaryRow}>
            <View>
              <Text style={styles.summaryLabel}>Total Pending</Text>
              <Text style={styles.summaryAmount}>₹{totalOwed.toFixed(2)}</Text>
            </View>
            <Text style={styles.summaryEmoji}>💰</Text>
          </View>
          <Text style={styles.summarySubtitle}>
            {debts.length} {debts.length === 1 ? 'person owes' : 'people owe'} you money
          </Text>
          <TouchableOpacity style={styles.bulkShareBtn} onPress={shareBulkReminder}>
            <Text style={styles.bulkShareIcon}>📤</Text>
            <Text style={styles.bulkShareText}>Share All Reminders</Text>
          </TouchableOpacity>
        </GlassCard>

        <Text style={styles.sectionTitle}>Individual Reminders</Text>
        {debts.map((debt, idx) => (
          <GlassCard key={idx} style={styles.debtCard} variant="default">
            <View style={styles.debtHeader}>
              <View style={styles.avatarRow}>
                <View style={styles.avatar}>
                  <Text style={styles.avatarText}>
                    {debt.fromName.charAt(0).toUpperCase()}
                  </Text>
                </View>
                <View>
                  <Text style={styles.debtPersonName}>{debt.fromName}</Text>
                  <Text style={styles.debtGroup}>{debt.groupName}</Text>
                </View>
              </View>
              <View style={styles.debtAmountBadge}>
                <Text style={styles.debtAmountText}>
                  {debt.currency}{debt.amount.toFixed(2)}
                </Text>
              </View>
            </View>

            <View style={styles.expenseList}>
              {debt.expenses.map((exp, i) => (
                <View key={i} style={styles.expenseRow}>
                  <Text style={styles.expenseDot}>▸</Text>
                  <Text style={styles.expenseName}>{exp}</Text>
                </View>
              ))}
            </View>

            <View style={styles.messagePreview}>
              <Text style={styles.previewLabel}>Message Preview</Text>
              <Text style={styles.previewText} numberOfLines={4}>
                {generateWhatsAppMessage(debt)}
              </Text>
            </View>

            <View style={styles.actionRow}>
              <TouchableOpacity
                style={styles.copyBtn}
                onPress={() => copyToClipboard(debt)}
              >
                <Text style={styles.copyBtnText}>📋 Copy</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.shareBtn}
                onPress={() => shareReminder(debt)}
              >
                <Text style={styles.shareBtnIcon}>📤</Text>
                <Text style={styles.shareBtnText}>Share via WhatsApp / SMS</Text>
              </TouchableOpacity>
            </View>
          </GlassCard>
        ))}

        <GlassCard style={styles.tipCard} padding={12}>
          <Text style={styles.tipTitle}>💡 Quick Settle Tips</Text>
          <Text style={styles.tipText}>
            • Share your UPI ID or QR code in the message{'\n'}
            • Messages include expense breakdown for context{'\n'}
            • Mark as settled manually after payment received
          </Text>
        </GlassCard>

        <View style={{ height: 120 }} />
      </ScrollView>
    </View>
  );
};

export default SettlementReminderScreen;
